- name: Parar o Apache -  LIKE DEBIAN
  service:
    name: apache2
    state: stopped
  when: ansible_os_family == "Debian"

- name: Removendo Apache - LIKE DEBIAN
  apt:
    name: apache2*
    state: absent
  when: ansible_os_family == "Debian"	
    
