---
- name: Desafio1
  hosts: all
  tasks:
    - name: Parar NGINX
      service:
        name: nginx
        state: stopped
      ignore_errors: True

    - name: Removendo NGINX - UBUNTU
      apt:
        name: nginx*
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: Removendo NGINX - CENTOS
      yum:
        name: nginx*
        state: absent
      when: ansible_distribution == "CentOS"

    - name: Instalando Servidor Web - UBUNTU
      apt:
        name: ['apache2','libapache2-mod-php7.0','php7.0']
        state: present
        update_cache: yes
      notify: apache
      when: ansible_distribution == "Ubuntu"

    - name: Ativando Modulo PHP - UBUNTU
      command: a2enmod php7.0
      notify: apache
      when: ansible_distribution == "Ubuntu"


    - name: Instalando Servidor Web - CENTOS
      yum:
        name: ['httpd','php']
        state: present
      notify: httpd
      when: ansible_distribution == "CentOS"

    - name: Copiando Index.php
      copy:
        src: /etc/ansible/index.php
        dest: /var/www/html/index.php

  handlers:
    - name: httpd
      service:
        name: httpd
        state: restarted

    - name: apache
      service:
        name: apache2
        state: restarted
       


