---
- name: Install Rundeck
  hosts: automation
  tasks:
    - name: Add Repositorio Rundeck
      yum:
        name: http://repo.rundeck.org/last.rpm
        state: present
      register: result

    - name: Mostrando Resultado
      debug:
        var: result.stdout

    - name: Install Rundeck
      yum:
        name: ['java-1.8.0','rundeck']
        state: present


